[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:backend]
command=java
    --add-opens=jdk.jshell/jdk.jshell=ALL-UNNAMED
    --add-exports=jdk.jshell/jdk.jshell=ALL-UNNAMED
    -Xmx380m
    -Xms64m
    -XX:+UseG1GC
    -XX:MaxGCPauseMillis=200
    -XX:MaxMetaspaceSize=128m
    -Djava.security.egd=file:/dev/./urandom
    -jar /app/backend.jar
autostart=true
autorestart=true
startsecs=10
startretries=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
startsecs=2
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
